### ISSUE TITLE
Mouse becomes unusable on the desktop with a gamepad plugged in

### ISSUE THREAD

**Issue by scrawl** [jazztickets/irrlamb#9]
Irrlamb moves around the mouse for me when I move the gamepad stick. That's a good feature, but it should stop doing that when I'm alt-tabbed out of the game (i.e. the game window isn't in the foreground).

**Comment by jazztickets** [comment]
fixed in trunk

**Comment by scrawl** [comment]
It's not fixed for me.

```irrDevice->isWindowActive()``` only returns false when the window is minimized.

I tried using  ```irrDevice->isWindowFocused()```. That sometimes works, but sometimes returns 1 even though the window isn't focused. Irrlicht bug?

**Comment by jazztickets** [comment]
Are you saying your mouse completely stops working when you're alt-tabbed or is this related to the deadzone issue where the mouse still moves a bit from the joystick input?

Does "xinput test-xi2 | grep Focus" work for you? Are you fullscreen?

What if you pause the game first then alt-tab?

**Comment by scrawl** [comment]
> Are you saying your mouse completely stops working when you're alt-tabbed

If the stick is slightly off-center then I can't use the mouse any more because the game keeps warping the cursor back to the previous position (meanwhile very slowly moving the cursor).

If the stick is completely centered there is no issue. So yes, you could say it's related to the deadzone issue, although a separate fix for not emulating mouse movement when the game window isn't focused would still be nice.

I added a deadzone into the code that effectively solves the issue for me.

> Are you fullscreen?

No, if I'm full screen then alt-tab doesn't work, like in old SDL 1.2 games. Is Irrlicht using SDL 1.2?

> What if you pause the game first then alt-tab?

No change.

**Comment by scrawl** [comment]
<pre>
xinput test-xi2 | grep Focus
</pre>
Yes, I get FocusIn and FocusOut messages as expected.

**Comment by jazztickets** [comment]
So I added the deadzone per-axis in the config file. Maybe this'll fix it for you. Delete your existing joystick .xml file so it can regenerate, then you can increase the deadzone value from the original 0.05 value.

I'm just using the default CIrrDeviceLinux.cpp class. Maybe switching to their sdl device will fix some things but it's SDL 1.x which still has bad alt-tab support. Ideally i'd use RawMotion events but irrlicht hasn't updated their X11 code in forever.
